name: Publish package to Hex.pm

on:
  release:
    types: [published, released]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.17.2'
        otp-version: '26.2.5.2'

    - name: Install dependencies
      run: |
        mix deps.get

    - name: Publish to Hex.pm
      env:
        HEX_API_KEY: ${{ secrets.HEXPM_PUBLIC_PACKAGES_KEY }}
      run: |
        mix hex.build
        mix hex.publish --yes
